<?php

return [
    'page' => [
        'width_mm'    => 297,
        'height_mm'   => 210,
        'width_px'    => 2000,
        'height_px'   => 1414,
        'orientation' => 'landscape',
    ],

    'templates' => [
        'PARTICIPATION' => [
            'type'        => 'PARTICIPATION',
            'name'        => 'شهادة مشاركة رسمية',
            'version'     => '1.0',
            'background'  => 'certificates/participation_bg.png',
            'sha256'      => '567FF63168D1095B49AF7CF2A4F79E143603AA68DAA2C2A6D32EE4E79EF394A2',
            'fields' => [
                'recipient_name_ar' => [
                    'top_pct'     => 57.8,
                    'left_pct'    => 35.0,
                    'width_pct'   => 32.0,
                    'font_size'   => '1.6rem',
                    'font_weight' => '900',
                    'color'       => '#06205C',
                    'align'       => 'center',
                    'direction'   => 'rtl',
                ],
                'recipient_name_latin' => [
                    'top_pct'     => 61.8,
                    'left_pct'    => 35.0,
                    'width_pct'   => 32.0,
                    'font_size'   => '0.95rem',
                    'font_weight' => '700',
                    'color'       => '#0284C7',
                    'align'       => 'center',
                    'direction'   => 'ltr',
                ],
                'date' => [
                    'top_pct'     => 91.0,
                    'right_pct'   => 17.5,
                    'font_size'   => '0.9rem',
                    'font_weight' => '700',
                    'color'       => '#06205C',
                    'direction'   => 'rtl',
                ],
                'serial' => [
                    'top_pct'     => 2.5,
                    'left_pct'    => 4.0,
                    'font_size'   => '0.75rem',
                    'font_weight' => '800',
                    'color'       => '#475569',
                    'direction'   => 'ltr',
                ],
                'qr' => [
                    'top_pct'     => 84.0,
                    'left_pct'    => 4.5,
                    'size_px'     => 85,
                ],
            ],
        ],

        'PARTNER' => [
            'type'        => 'PARTNER',
            'name'        => 'شهادة تقدير للشركاء الاقتصاديين',
            'version'     => '1.0',
            'background'  => 'certificates/partner_bg.png',
            'sha256'      => '108E277C14D85468121D823554B72D2CBC7C5E9DBDD644058746F9388E1B8523',
            'fields' => [
                'recipient_name_ar' => [
                    'top_pct'     => 57.8,
                    'left_pct'    => 35.0,
                    'width_pct'   => 32.0,
                    'font_size'   => '1.6rem',
                    'font_weight' => '900',
                    'color'       => '#06205C',
                    'align'       => 'center',
                    'direction'   => 'rtl',
                ],
                'recipient_name_latin' => [
                    'top_pct'     => 61.8,
                    'left_pct'    => 35.0,
                    'width_pct'   => 32.0,
                    'font_size'   => '0.95rem',
                    'font_weight' => '700',
                    'color'       => '#0284C7',
                    'align'       => 'center',
                    'direction'   => 'ltr',
                ],
                'date' => [
                    'top_pct'     => 91.0,
                    'right_pct'   => 17.5,
                    'font_size'   => '0.9rem',
                    'font_weight' => '700',
                    'color'       => '#06205C',
                    'direction'   => 'rtl',
                ],
                'serial' => [
                    'top_pct'     => 2.5,
                    'left_pct'    => 4.0,
                    'font_size'   => '0.75rem',
                    'font_weight' => '800',
                    'color'       => '#475569',
                    'direction'   => 'ltr',
                ],
                'qr' => [
                    'top_pct'     => 84.0,
                    'left_pct'    => 4.5,
                    'size_px'     => 85,
                ],
            ],
        ],

        'APPRECIATION' => [
            'type'        => 'APPRECIATION',
            'name'        => 'شهادة شكر وتقدير عامة',
            'version'     => '1.0',
            'background'  => 'certificates/appreciation_bg.png',
            'sha256'      => '45A67916ED2820E21DCAAC6DFBC7FB4FFD819FF90828570A6690A276E7BB0CF4',
            'fields' => [
                'recipient_name_ar' => [
                    'top_pct'     => 57.8,
                    'left_pct'    => 35.0,
                    'width_pct'   => 32.0,
                    'font_size'   => '1.6rem',
                    'font_weight' => '900',
                    'color'       => '#06205C',
                    'align'       => 'center',
                    'direction'   => 'rtl',
                ],
                'recipient_name_latin' => [
                    'top_pct'     => 61.8,
                    'left_pct'    => 35.0,
                    'width_pct'   => 32.0,
                    'font_size'   => '0.95rem',
                    'font_weight' => '700',
                    'color'       => '#0284C7',
                    'align'       => 'center',
                    'direction'   => 'ltr',
                ],
                'date' => [
                    'top_pct'     => 91.0,
                    'right_pct'   => 17.5,
                    'font_size'   => '0.9rem',
                    'font_weight' => '700',
                    'color'       => '#06205C',
                    'direction'   => 'rtl',
                ],
                'serial' => [
                    'top_pct'     => 2.5,
                    'left_pct'    => 4.0,
                    'font_size'   => '0.75rem',
                    'font_weight' => '800',
                    'color'       => '#475569',
                    'direction'   => 'ltr',
                ],
                'qr' => [
                    'top_pct'     => 84.0,
                    'left_pct'    => 4.5,
                    'size_px'     => 85,
                ],
            ],
        ],
    ],
];
